version: 2
jobs:
  build:
    working_directory: ~/mockup
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: mockup-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: mockup-{{ checksum "pom.xml" }}
      - run:
          command:  mvn package
          environment:
            SERVER_PORT: 7070
            LOG_LEVEL: info
            WEB_LOG_LEVEL: info
            DATABASE_HOST: mongodb://localhost:27017/mongoDbTest
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
